### ISSUE TITLE
Contacts application cannot authenticate

### ISSUE THREAD

**Issue by nicodel** [cozy/cozy-contacts#115]
Hi,

Cozy Cloud instance hosted on Cozy infrastructure (nicolas-6)
Data System: 2.0.6
Proxy: 2.0.2
Home: 2.0.4
Controller: 2.0.27

When I launch the Contacts application, it is appears empty. and when I look at the Contacts logs I have the following:

```
[2015-07-20 21:41:08:172] error - Cozy DB | A request creation failed, abandon.
[2015-07-20 21:41:08:173] error - americano | cozydb failed to load.
Error: { error: 'Application is not authenticated' }
    at /usr/local/cozy/apps/contacts/node_modules/cozydb/lib/cozymodel.js:252:27
    at parseBody (/usr/local/cozy/apps/contacts/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/contacts/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
Error: { error: 'Application is not authenticated' }
    at /usr/local/cozy/apps/contacts/node_modules/cozy[Tue, 21 Jul 2015 06:52:57 GMT] - GET /tags - 500 - 10.772 ms -  -
[Tue, 21 Jul 2015 07:45:13 GMT] - GET / - 200 - 8.217 ms -  2360
[Tue, 21 Jul 2015 07:45:15 GMT] - GET /contacts - 500 - 4.759 ms -  -
[Tue, 21 Jul 2015 07:45:15 GMT] - GET /tags - 500 - 8.746 ms -  -
99:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
Error: { error: 'Application is not authenticated' }
    at /usr/local/cozy/apps/contacts/node_modules/cozydb/lib/cozymodel.js:252:27
    at parseBody (/usr/local/cozy/apps/contacts/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/contacts/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
Error: { error: 'Application is not authenticated' }
    at /usr/local/cozy/apps/contacts/node_modules/cozydb/lib/cozymodel.js:252:27
    at parseBody (/usr/local/cozy/apps/contacts/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/contacts/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
cess._tickCallback (node.js:448:13)
Error: { error: 'Application is not authenticated' }
    at /usr/local/cozy/apps/contacts/node_modules/cozydb/lib/cozymodel.js:252:27
    at parseBody (/usr/local/cozy/apps/contacts/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/contacts/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```
I did not try to relaunch or reboot the instance yet, because if I understood well, Cozy staff is looking at more data for this authentication issue.
Hope it helps.

**Comment by poupotte** [comment]
Thanks @nicodel for your report.

I'm working on this issue. I hope have a correction today.
Acutally, I have enough information so don't hesitate to reinstall your application. 

Thanks for your patience :)

**Comment by clochix** [comment]
Thanks for reporting @nicodel. @poupotte is working on it and we already have lots of other issues on this, so I hope you won't mind if I close this one.

**Comment by nicodel** [comment]
AAAaaaaah (no it's ok :))
