### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-contacts#118]
Here are the logs:
```
TypeError: Object #<Object> has no method 'getComputedFN'
    at Function.module.exports.Contact.cast (/usr/local/cozy/apps/contacts/build/server/models/contact.js:69:26)
    at Function.Model.create (/usr/local/cozy/apps/contacts/node_modules/cozydb/lib/model.js:67:19)
    at create (/usr/local/cozy/apps/contacts/build/server/controllers/contact.js:39:22)
    at Object.module.exports.create [as handle] (/usr/local/cozy/apps/contacts/build/server/controllers/contact.js:72:14)
    at next_layer (/usr/local/cozy/apps/contacts/node_modules/americano/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/usr/local/cozy/apps/contacts/node_modules/americano/node_modules/express/lib/router/route.js:107:5)
    at /usr/local/cozy/apps/contacts/node_modules/americano/node_modules/express/lib/router/index.js:213:24
    at Function.proto.process_params (/usr/local/cozy/apps/contacts/node_modules/americano/node_modules/express/lib/router/index.js:284:12)
    at next (/usr/local/cozy/apps/contacts/node_modules/americano/node_modules/express/lib/router/index.js:207:19)
    at next_layer (/usr/local/cozy/apps/contacts/node_modules/americano/node_modules/express/lib/router/route.js:77:14)

```

STR: click on + to add a new contact and try to set its misc information without setting a name.

**Comment by clochix** [comment]
A user also [hit this one](https://forum.cozy.io/t/probleme-de-sauvegarde-des-notes-dun-contact-quand-elles-sont-tapees/1073/2) so I fixed it.
