### ISSUE TITLE
TypeError: Cannot read property 'attr' of undefined

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-contacts#249]
On client side.
According to the error stack, seems to be in [appLayout.error](https://github.com/cozy/cozy-contacts/blob/7990ea0de6ee686f16f12cc2a9da70db7d70a0f6/client/app/views/app_layout.coffee#L217) when error is `ERR.SEARCH_TOO_SHORT`.

Also, the translation of `error search too short` some lines after seems missing.

**Comment by clochix** [comment]
Another error stack (see #301):
```
error - contact:application | {"type":"error","href":"https://92.cozycloud.cc/apps/contacts/#contacts","url":"https://92.cozycloud.cc/apps/contacts/scripts/app.js","line":"4","col":"21393"}
error - contact:application | Uncaught TypeError: Cannot read property 'attr' of undefined
error - contact:application | TypeError: Cannot read property 'attr' of undefined
    at o.exports.o.error (https://92.cozycloud.cc/apps/contacts/scripts/app.js:4:21393)
    at v (https://92.cozycloud.cc/apps/contacts/scripts/vendor.js:4:24462)
    at y (https://92.cozycloud.cc/apps/contacts/scripts/vendor.js:4:24254)
    at f (https://92.cozycloud.cc/apps/contacts/scripts/vendor.js:4:22173)
    at l.trigger (https://92.cozycloud.cc/apps/contacts/scripts/vendor.js:4:24147)
    at o.keyup @ui.search._.debounce.trailing (https://92.cozycloud.cc/apps/contacts/scripts/app.js:7:7382)
    at o.a (https://92.cozycloud.cc/apps/contacts/scripts/vendor.js:1:28026)
    at HTMLInputElement.n (https://92.cozycloud.cc/apps/contacts/scripts/vendor.js:1:13954)
    at HTMLLabelElement.dispatch (https://92.cozycloud.cc/apps/contacts/scripts/vendor.js:3:29045)
    at HTMLLabelElement.m.handle (https://92.cozycloud.cc/apps/contacts/scripts/vendor.js:3:25828)
[Fri, 30 Sep 2016 10:08:31 GMT] - POST /log - 204 - 0.517 ms -  -
```
