### ISSUE TITLE
Error: Failed to execute 'insertRule' on 'CSSStyleSheet'

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-contacts#262]
See rems errors in [this feed](https://forum.cozy.io/t/app-contacts/1103):

```
error - contact:application | {"type":"error","href":"https://remylicot.cozycloud.cc/apps/contacts/#tags/prof physique","url":"https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js","line":"4","col":"3959"}
error - contact:application | Uncaught SyntaxError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '[role=row]:not(.tag_prof physique),
[role=rowgroup]:not(.tag_prof physique) { display: none }'.
error - contact:application | Error: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '[role=row]:not(.tag_prof physique),
[role=rowgroup]:not(.tag_prof physique) { display: none }'.
    at Error (native)
    at o.exports.o.filter (https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js:4:3959)
    at o.n.extend.execute (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:5:5577)
    at Object.callback (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:5:5419)
    at https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:5:9535
    at fe (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:1:5807)
    at Function.si (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:1:26887)
    at n.extend.loadUrl (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:5:9478)
    at n.extend.navigate (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:5:10228)
    at o.n.extend.navigate (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:5:5632)
```

**Comment by gregorylegarec** [comment]
__Reproduce__ : 
* Create a new label containing a space character (in this case, "Prof physique")
* On the left panel, select this new label
* The error is thrown

__Expected behavior__ : 
* The slug variable used in filters should not contain space character. Also, the class applied to the contact's DOM element also contains this space and is not "slugified".

**Comment by gregorylegarec** [comment]
Should be fixed by https://github.com/cozy/cozy-contacts/pull/288
