### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-contacts#263]
See rems errors in [this feed](https://forum.cozy.io/t/app-contacts/1103):

```
error - contact:application | {"type":"error","href":"https://remylicot.cozycloud.cc/apps/contacts/#tags/prof physique","url":"https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js","line":"0","col":"0"}
error - contact:application | Uncaught TypeError: undefined is not a function
error - contact:application | TypeError: undefined is not a function
    at Object.e.match (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:7:4299)
    at https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js:3:30935
    at Array.reduce (native)
    at o.exports.o.match (https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js:3:30891)
    at https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js:1:5774
    at l (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:1:17069)
    at ae (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:1:5383)
    at Function.Kr (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:1:26032)
    at o.filter (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:4:21442)
    at t.o.exports.t.setQuery (https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js:1:6919)
```

**Comment by gregorylegarec** [comment]
I assume that the call responsible of this error is this one:
https://github.com/cozy/cozy-contacts/blob/master/client/app/models/contact.coffee#L185

But I am not able to reproduce the error. It seems that it is caused by the global variable `fuzzy` being `undefined`.
