### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-contacts#265]
See rems errors in [this feed](https://forum.cozy.io/t/app-contacts/1103):

```
error - contact:application | {"type":"error","href":"https://remylicot.cozycloud.cc/apps/contacts/#contacts","url":"https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js","line":"4","col":"69"}
error - contact:application | Uncaught TypeError: Cannot read property 'length' of null
error - contact:application | TypeError: Cannot read property 'length' of null
    at o.exports.o.toggleResults (https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js:4:7598)
    at v (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:4:24520)
    at y (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:4:24254)
    at f (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:4:22173)
    at l.trigger (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:4:24147)
    at o.search (https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js:1:2650)
    at o.keyup @ui.search._.debounce.trailing (https://remylicot.cozycloud.cc/apps/contacts/scripts/app.js:6:23636)
    at i (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:1:27782)
    at s (https://remylicot.cozycloud.cc/apps/contacts/scripts/vendor.js:1:27878)

```

**Comment by gregorylegarec** [comment]
__Reproduce__ :
* Set cursor into search field
* Don't type any string
* Press enter
