### ISSUE TITLE
Contacts export results in cozy-light stopping

### ISSUE THREAD

**Issue by marthjod** [cozy/cozy-contacts#51]
Fresh install, Contacts app v1.0.10. Reproduce: On, e.g., [http://localhost:19104/apps/cozy-contacts/#help](http://localhost:19104/apps/cozy-contacts/#help), choose "Click here to export all your contacts as a vCard file: Export vCard file". 
Result:

```
warn - Cozy Light | An exception is uncaught
[ReferenceError: initial is not defined]
ReferenceError: initial is not defined
    at ModelConstructor.Contact.getComputedFN (/home/marcin/.cozy-light/node_modules/cozy-contacts/server/models/contact.js:47:34)
    at ModelConstructor.Contact.toVCF (/home/marcin/.cozy-light/node_modules/cozy-contacts/server/models/contact.js:61:26)
    at /home/marcin/.cozy-light/node_modules/cozy-contacts/server/controllers/contact.js:124:26
    at /home/marcin/.cozy-light/node_modules/cozy-contacts/node_modules/americano-cozy-pouchdb/node_modules/jugglingdb-pouchdb-adapter/lib/pouchdb.js:429:20
    at /usr/lib/node_modules/cozy-light/node_modules/pouchdb/node_modules/pouchdb-mapreduce/utils.js:25:9
    at process._tickCallback (node.js:419:13)
info - Cozy Light | Stopping apps...
info - Cozy Light | 	✓	Contacts
info - Cozy Light | 	✓	Files
info - Cozy Light | Stopping plugins...
info - Cozy Light | 	✓	Simple Dashboard
info - Cozy Light | 	✓	Auth Plugin
info - Cozy Light | Stopping server...
info - Cozy Light | 	✓	main server
info - Cozy Light | Cozy Light was properly terminated.
GET /contacts.vcf - - ms - -
{ [Error: socket hang up] code: 'ECONNRESET' }
```

This is the start-up output:

```
% cozy-light start                     
info - Cozy Light | Configuring plugin cozy-labs/cozy-light-simple-dashboard...
info - Cozy Light | Plugin cozy-labs/cozy-light-simple-dashboard configured.
info - Cozy Light | Configuring plugin cozy-labs/cozy-light-auth...
info - Cozy Light | Plugin cozy-labs/cozy-light-auth configured.
info - Cozy Light | Cozy Light server is listening on port 19104...
[2015-01-03 01:56:17:938] info - helper/db_feed | Pub server started
   info  - socket.io started
info - Cozy Light | Application cozy-files is now running on port 18001...
An error occurred while initializing notification module -- Error: connect ECONNREFUSED
info - Cozy Light | Application cozy-contacts is now running on port 18002...
```

**Comment by frankrousseau** [comment]
Hi @marthjod. Thank you for reporting. 

The Cozy Contact application for Cozy Light was not up to date. I updated it with latest standard Cozy version. You can try to uninstall/install it again.

**Comment by frankrousseau** [comment]
Hi @marthjod do you have any news about that?
